language: python

addons:
  apt:
    packages:
    - protobuf-compiler

before_install:
  - protoc --python_out=pyBluzelle/pyBluzelle/proto --proto_path=pybluzelle/proto/proto bluzelle.proto database.proto audit.proto

python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below