language: python


before_install:
  - sudo apt-get install -y ptotobuf-dev

python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below