version: '3'

services:
  swarm01:
    image: bluzelle/swarmdb:alpha
    ports:
      - "51010:51010"
    environment:
      SWARM_UUID: "92b8bac6-3242-452a-9090-1aa48afd71a3"
      SWARM_NAME: "swarm01"
      SWARM_PORT: "51010"
      SWARM_BOOTSTRAP_URL: "http://pastebin.com/raw/AuYYbMWn"
    expose:
      - "51010"
    networks:
      swarmnet:
        ipv4_address: 10.5.0.4
    volumes:
      - /tmp:/tmp/swarm_home

  swarm02:
    image: bluzelle/swarmdb:alpha
    ports:
      - "51011:51011"
    environment:
      SWARM_UUID: "c864516b-3c95-4721-ad3e-a8dccd0d8349"
      SWARM_NAME: "swarm02"
      SWARM_PORT: "51011"
      SWARM_BOOTSTRAP_URL: "http://pastebin.com/raw/AuYYbMWn"
    expose:
      - "51011"
    networks:
      swarmnet:
        ipv4_address: 10.5.0.5
    volumes:
      - /tmp:/tmp/swarm_home

  swarm03:
      image: bluzelle/swarmdb:alpha
      ports:
        - "51012:51012"
      environment:
        SWARM_UUID: "137a8403-52ec-43b7-8083-91391d4c5e67"
        SWARM_NAME: "swarm03"
        SWARM_PORT: "51012"
        SWARM_BOOTSTRAP_URL: "http://pastebin.com/raw/AuYYbMWn"
      expose:
        - "51012"
      networks:
        swarmnet:
          ipv4_address: 10.5.0.6
      volumes:
        - /tmp:/tmp/swarm_home


networks:
  swarmnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16